[package]
name = "rhubarb"
version = "0.2.0"
authors = ["Cxarli <10348289+Cxarli@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
